# Generated by Django 5.1.7 on 2025-04-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ride", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$870000$guaagihducDIeumeDci7MR$kXEQ8wqCgEDoNE7GMBsB/Y+u+nGrEUvll2a8BVrFI94=",
                max_length=128,
            ),
        ),
    ]
