# Generated by Django 5.1.7 on 2025-04-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ride", "0002_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("passenger", "Passenger"), ("driver", "Driver")],
                default="passenger",
                max_length=10,
            ),
        ),
    ]
