# Generated by Django 5.1.7 on 2025-04-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ride", "0003_alter_user_password_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("passenger", "Passenger"), ("driver", "Driver")],
                max_length=10,
            ),
        ),
    ]
